# Generated by Django 4.2.16 on 2024-10-15 20:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_vote_unique_together_restaurant_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
